services:
  simulador:
    build: .
    container_name: agrosmart_simulador
    command: python mvp/producer_simulator.py
    volumes:
      - .:/app

  processador_ia:
    build: .
    container_name: agrosmart_ia
    command: python mvp/consumer.py --model_path models/maize_densenet121_state_dict.pt --meta_path models/maize_densenet121_meta.json
    volumes:
      - .:/app
    depends_on:
      - simulador
